/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoestru2;

import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;

/**
 *
 * @author samue
 */
public class Proy extends javax.swing.JFrame {

    /**
     * Creates new form Proy
     */
    public Proy() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        Menu.setLayout(new CardLayout());
        MenuMenus.setLayout(new CardLayout());
        jtb_Campos.setLayout(new CardLayout());
        jtp_registros.setLayout(new CardLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_seleccion = new javax.swing.JPanel();
        jb_archivos = new javax.swing.JButton();
        jb_campos = new javax.swing.JButton();
        jb_registros = new javax.swing.JButton();
        jb_indices = new javax.swing.JButton();
        jb_estandarizacion = new javax.swing.JButton();
        jb_cerrar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Menu = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jb_nuevoArchivo = new javax.swing.JButton();
        jb_abrirArchivo = new javax.swing.JButton();
        jb_salvarArchivo = new javax.swing.JButton();
        jb_cerrarArchivo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jb_crearCampos = new javax.swing.JButton();
        jb_ListarCampos = new javax.swing.JButton();
        jb_modificarCampos = new javax.swing.JButton();
        jb_EliminarCampos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jb_nuevoArchivo1 = new javax.swing.JButton();
        jb_abrirArchivo1 = new javax.swing.JButton();
        jb_salvarArchivo1 = new javax.swing.JButton();
        jb_cerrarArchivo1 = new javax.swing.JButton();
        jb_cerrarArchivo2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jb_nuevoArchivo3 = new javax.swing.JButton();
        jb_abrirArchivo3 = new javax.swing.JButton();
        jb_salvarArchivo3 = new javax.swing.JButton();
        jb_cerrarArchivo4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jb_nuevoArchivo2 = new javax.swing.JButton();
        jb_abrirArchivo2 = new javax.swing.JButton();
        jb_salvarArchivo2 = new javax.swing.JButton();
        jb_cerrarArchivo3 = new javax.swing.JButton();
        MenuMenus = new javax.swing.JTabbedPane();
        jp_archivos = new javax.swing.JPanel();
        jp_campos = new javax.swing.JPanel();
        jtb_Campos = new javax.swing.JTabbedPane();
        jp_crearCampos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_nombreCampo = new javax.swing.JTextField();
        jl_longitud = new javax.swing.JLabel();
        js_longitud = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jcb_tipoDeDato = new javax.swing.JComboBox<>();
        jl_llavePrimaria = new javax.swing.JLabel();
        jcb_llavePrimaria = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jp_listarCampos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_listarCampos = new javax.swing.JTable();
        jp_modificarCampos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_modificarCampos = new javax.swing.JTable();
        jb_modificarCampo = new javax.swing.JButton();
        jp_eliminarCampos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_eliminarCampo = new javax.swing.JList<>();
        jb_eliminarCampo = new javax.swing.JButton();
        jp_registros = new javax.swing.JPanel();
        jtp_registros = new javax.swing.JTabbedPane();
        jp_introducirregistros = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_introR = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_buscarR = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_listarRegistro = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_crearIndice = new javax.swing.JList<>();
        jb_nuevoArchivo4 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jp_seleccion.setBackground(new java.awt.Color(102, 102, 102));

        jb_archivos.setBackground(new java.awt.Color(204, 255, 255));
        jb_archivos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_archivos.setText("Archivos");
        jb_archivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_archivosActionPerformed(evt);
            }
        });

        jb_campos.setBackground(new java.awt.Color(204, 204, 255));
        jb_campos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_campos.setText("Campos");
        jb_campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_camposActionPerformed(evt);
            }
        });

        jb_registros.setBackground(new java.awt.Color(255, 204, 204));
        jb_registros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_registros.setText("Registros");
        jb_registros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registrosActionPerformed(evt);
            }
        });

        jb_indices.setBackground(new java.awt.Color(255, 255, 204));
        jb_indices.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_indices.setText("Indices");
        jb_indices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_indicesActionPerformed(evt);
            }
        });

        jb_estandarizacion.setBackground(new java.awt.Color(204, 255, 204));
        jb_estandarizacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_estandarizacion.setText("Estand.");
        jb_estandarizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_estandarizacionActionPerformed(evt);
            }
        });

        jb_cerrar.setBackground(new java.awt.Color(255, 102, 102));
        jb_cerrar.setText("Cerrar");
        jb_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cerrarActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(153, 204, 255));
        jButton7.setText("Regresar");

        javax.swing.GroupLayout jp_seleccionLayout = new javax.swing.GroupLayout(jp_seleccion);
        jp_seleccion.setLayout(jp_seleccionLayout);
        jp_seleccionLayout.setHorizontalGroup(
            jp_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_seleccionLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jb_archivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jb_campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jb_registros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jb_indices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jb_estandarizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addGroup(jp_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_seleccionLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jb_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jp_seleccionLayout.setVerticalGroup(
            jp_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_seleccionLayout.createSequentialGroup()
                .addGroup(jp_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_seleccionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jb_cerrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7))
                    .addGroup(jp_seleccionLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jp_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_archivos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_campos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_indices, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_estandarizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Menu.setBackground(new java.awt.Color(102, 102, 102));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jb_nuevoArchivo.setText("Crear Archivo");
        jb_nuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_nuevoArchivoActionPerformed(evt);
            }
        });

        jb_abrirArchivo.setText("Abrir Archivo");
        jb_abrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_abrirArchivoActionPerformed(evt);
            }
        });

        jb_salvarArchivo.setText("Salvar Archivo");
        jb_salvarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarArchivoActionPerformed(evt);
            }
        });

        jb_cerrarArchivo.setText("Cerrar Archivo");
        jb_cerrarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cerrarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_cerrarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_salvarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_abrirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_nuevoArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jb_nuevoArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_abrirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_salvarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_cerrarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        Menu.addTab("tab1", jPanel4);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jb_crearCampos.setText("Crear");
        jb_crearCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearCamposActionPerformed(evt);
            }
        });

        jb_ListarCampos.setText("Listar");
        jb_ListarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ListarCamposActionPerformed(evt);
            }
        });

        jb_modificarCampos.setText("Modificar");
        jb_modificarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarCamposActionPerformed(evt);
            }
        });

        jb_EliminarCampos.setText("Eliminar");
        jb_EliminarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_EliminarCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_EliminarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_modificarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_ListarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_crearCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jb_crearCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_ListarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_modificarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_EliminarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        Menu.addTab("tab2", jPanel1);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        jb_nuevoArchivo1.setText("Introducir");
        jb_nuevoArchivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_nuevoArchivo1ActionPerformed(evt);
            }
        });

        jb_abrirArchivo1.setText("Modificar");
        jb_abrirArchivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_abrirArchivo1ActionPerformed(evt);
            }
        });

        jb_salvarArchivo1.setText("Buscar");
        jb_salvarArchivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarArchivo1ActionPerformed(evt);
            }
        });

        jb_cerrarArchivo1.setText("Eliminar");
        jb_cerrarArchivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cerrarArchivo1ActionPerformed(evt);
            }
        });

        jb_cerrarArchivo2.setText("Listar");
        jb_cerrarArchivo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cerrarArchivo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_cerrarArchivo2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_cerrarArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_salvarArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_abrirArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_nuevoArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_nuevoArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_abrirArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_salvarArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_cerrarArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jb_cerrarArchivo2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Menu.addTab("tab3", jPanel3);

        jb_nuevoArchivo3.setText("Crear Indice");
        jb_nuevoArchivo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_nuevoArchivo3ActionPerformed(evt);
            }
        });

        jb_abrirArchivo3.setText("Reindexar");
        jb_abrirArchivo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_abrirArchivo3ActionPerformed(evt);
            }
        });

        jb_salvarArchivo3.setText("Salvar Archivo");
        jb_salvarArchivo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarArchivo3ActionPerformed(evt);
            }
        });

        jb_cerrarArchivo4.setText("Cerrar Archivo");
        jb_cerrarArchivo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cerrarArchivo4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_cerrarArchivo4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_salvarArchivo3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_abrirArchivo3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_nuevoArchivo3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jb_nuevoArchivo3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_abrirArchivo3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_salvarArchivo3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_cerrarArchivo4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        Menu.addTab("tab4", jPanel5);

        jb_nuevoArchivo2.setText("Exportar Excel");
        jb_nuevoArchivo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_nuevoArchivo2ActionPerformed(evt);
            }
        });

        jb_abrirArchivo2.setText("XML");
        jb_abrirArchivo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_abrirArchivo2ActionPerformed(evt);
            }
        });

        jb_salvarArchivo2.setText("Salvar Archivo");
        jb_salvarArchivo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarArchivo2ActionPerformed(evt);
            }
        });

        jb_cerrarArchivo3.setText("Cerrar Archivo");
        jb_cerrarArchivo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cerrarArchivo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_cerrarArchivo3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_salvarArchivo2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_abrirArchivo2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_nuevoArchivo2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jb_nuevoArchivo2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_abrirArchivo2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_salvarArchivo2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_cerrarArchivo3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        Menu.addTab("tab5", jPanel6);

        javax.swing.GroupLayout jp_archivosLayout = new javax.swing.GroupLayout(jp_archivos);
        jp_archivos.setLayout(jp_archivosLayout);
        jp_archivosLayout.setHorizontalGroup(
            jp_archivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jp_archivosLayout.setVerticalGroup(
            jp_archivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        MenuMenus.addTab("archivo", jp_archivos);

        jtb_Campos.setBackground(new java.awt.Color(51, 51, 51));

        jp_crearCampos.setBackground(new java.awt.Color(51, 51, 51));
        jp_crearCampos.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de Campo");

        jtf_nombreCampo.setBackground(new java.awt.Color(51, 51, 51));
        jtf_nombreCampo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtf_nombreCampo.setForeground(new java.awt.Color(204, 204, 204));
        jtf_nombreCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombreCampoActionPerformed(evt);
            }
        });
        jtf_nombreCampo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_nombreCampoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_nombreCampoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_nombreCampoKeyTyped(evt);
            }
        });

        jl_longitud.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jl_longitud.setForeground(new java.awt.Color(255, 255, 255));
        jl_longitud.setText("Longitud");

        js_longitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        js_longitud.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de Dato");

        jcb_tipoDeDato.setBackground(new java.awt.Color(51, 51, 51));
        jcb_tipoDeDato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcb_tipoDeDato.setForeground(new java.awt.Color(255, 255, 255));
        jcb_tipoDeDato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "String", "Boolean", "Integer", "Char ", "Double", "Float", "Short", "Byte" }));
        jcb_tipoDeDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_tipoDeDatoActionPerformed(evt);
            }
        });

        jl_llavePrimaria.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jl_llavePrimaria.setForeground(new java.awt.Color(255, 255, 255));
        jl_llavePrimaria.setText("Llave Primaria");

        jcb_llavePrimaria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_crearCamposLayout = new javax.swing.GroupLayout(jp_crearCampos);
        jp_crearCampos.setLayout(jp_crearCamposLayout);
        jp_crearCamposLayout.setHorizontalGroup(
            jp_crearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_crearCamposLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jp_crearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_llavePrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_llavePrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_nombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_tipoDeDato, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_crearCamposLayout.setVerticalGroup(
            jp_crearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_crearCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_nombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jl_longitud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_tipoDeDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jl_llavePrimaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_llavePrimaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtb_Campos.addTab("crear", jp_crearCampos);

        jp_listarCampos.setBackground(new java.awt.Color(51, 51, 51));

        jt_listarCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo de Dato", "Longitud", "Llave Primaria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_listarCampos);

        javax.swing.GroupLayout jp_listarCamposLayout = new javax.swing.GroupLayout(jp_listarCampos);
        jp_listarCampos.setLayout(jp_listarCamposLayout);
        jp_listarCamposLayout.setHorizontalGroup(
            jp_listarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_listarCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp_listarCamposLayout.setVerticalGroup(
            jp_listarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_listarCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtb_Campos.addTab("listar", jp_listarCampos);

        jt_modificarCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo de Dato", "Longitud", "Llave Primaria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_modificarCampos);

        jb_modificarCampo.setText("Modificar");
        jb_modificarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarCampoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_modificarCamposLayout = new javax.swing.GroupLayout(jp_modificarCampos);
        jp_modificarCampos.setLayout(jp_modificarCamposLayout);
        jp_modificarCamposLayout.setHorizontalGroup(
            jp_modificarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificarCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_modificarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                    .addGroup(jp_modificarCamposLayout.createSequentialGroup()
                        .addComponent(jb_modificarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jp_modificarCamposLayout.setVerticalGroup(
            jp_modificarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificarCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jb_modificarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jtb_Campos.addTab("modificar", jp_modificarCampos);

        jScrollPane3.setViewportView(jl_eliminarCampo);

        jb_eliminarCampo.setText("Eliminar");
        jb_eliminarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarCampoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_eliminarCamposLayout = new javax.swing.GroupLayout(jp_eliminarCampos);
        jp_eliminarCampos.setLayout(jp_eliminarCamposLayout);
        jp_eliminarCamposLayout.setHorizontalGroup(
            jp_eliminarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_eliminarCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jp_eliminarCamposLayout.createSequentialGroup()
                .addComponent(jb_eliminarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_eliminarCamposLayout.setVerticalGroup(
            jp_eliminarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_eliminarCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jb_eliminarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtb_Campos.addTab("eliminar", jp_eliminarCampos);

        javax.swing.GroupLayout jp_camposLayout = new javax.swing.GroupLayout(jp_campos);
        jp_campos.setLayout(jp_camposLayout);
        jp_camposLayout.setHorizontalGroup(
            jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtb_Campos)
        );
        jp_camposLayout.setVerticalGroup(
            jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtb_Campos)
        );

        MenuMenus.addTab("campo", jp_campos);

        jt_introR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jt_introR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jt_introR);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Crear Reigstros");

        jButton2.setText("Introducir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Crear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Introducir Registros");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Crear el Registro");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("o");

        javax.swing.GroupLayout jp_introducirregistrosLayout = new javax.swing.GroupLayout(jp_introducirregistros);
        jp_introducirregistros.setLayout(jp_introducirregistrosLayout);
        jp_introducirregistrosLayout.setHorizontalGroup(
            jp_introducirregistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_introducirregistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_introducirregistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_introducirregistrosLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_introducirregistrosLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                        .addGroup(jp_introducirregistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_introducirregistrosLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(jp_introducirregistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(87, 87, 87))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_introducirregistrosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))))
            .addGroup(jp_introducirregistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_introducirregistrosLayout.createSequentialGroup()
                    .addContainerGap(483, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
            .addGroup(jp_introducirregistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_introducirregistrosLayout.createSequentialGroup()
                    .addContainerGap(480, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(24, 24, 24)))
        );
        jp_introducirregistrosLayout.setVerticalGroup(
            jp_introducirregistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_introducirregistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_introducirregistrosLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jp_introducirregistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_introducirregistrosLayout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(302, Short.MAX_VALUE)))
            .addGroup(jp_introducirregistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_introducirregistrosLayout.createSequentialGroup()
                    .addContainerGap(241, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(141, 141, 141)))
        );

        jtp_registros.addTab("introducir", jp_introducirregistros);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jtp_registros.addTab("Modificar", jPanel8);

        jt_buscarR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jt_buscarR);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtp_registros.addTab("Buscar", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jtp_registros.addTab("Eliminar", jPanel10);

        jt_listarRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jt_listarRegistro);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jtp_registros.addTab("Listar", jPanel11);

        javax.swing.GroupLayout jp_registrosLayout = new javax.swing.GroupLayout(jp_registros);
        jp_registros.setLayout(jp_registrosLayout);
        jp_registrosLayout.setHorizontalGroup(
            jp_registrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtp_registros)
        );
        jp_registrosLayout.setVerticalGroup(
            jp_registrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtp_registros)
        );

        MenuMenus.addTab("registro", jp_registros);

        jl_crearIndice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane7.setViewportView(jl_crearIndice);

        jb_nuevoArchivo4.setText("Crear Arbol");
        jb_nuevoArchivo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_nuevoArchivo4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jb_nuevoArchivo4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jb_nuevoArchivo4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                .addContainerGap())
        );

        MenuMenus.addTab("indice", jPanel2);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        MenuMenus.addTab("Estand", jPanel12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_seleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuMenus)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu)
                    .addComponent(MenuMenus, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_camposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_camposActionPerformed
        if (archivo == null) {
            JOptionPane.showMessageDialog(this, "Debe abrir o crear un archivo");
        } else if (!arbol.getRoot().keys.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los campos no pueden cambiar cuando registros fueron añadidos");
        } else {
            Menu.setSelectedIndex(1);
            MenuMenus.setSelectedIndex(1);
        }

    }//GEN-LAST:event_jb_camposActionPerformed

    private void jb_indicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_indicesActionPerformed
        if (archivo == null) {
            JOptionPane.showMessageDialog(this, "Debe abrir o crear un archivo");
        } else {
            DefaultListModel lm = new DefaultListModel();
            lm.addAll(m.getLista());
            jl_crearIndice.setModel(lm);
            Menu.setSelectedIndex(3);
            MenuMenus.setSelectedIndex(3);

        }
    }//GEN-LAST:event_jb_indicesActionPerformed

    private void jb_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jb_cerrarActionPerformed

    private void jb_cerrarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cerrarArchivoActionPerformed
        if (archivo != null) {
            m = new MetaData();
            try {
                archivo.close();
            } catch (IOException ex) {
                Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
            }
            archivo = null;
            JOptionPane.showMessageDialog(null, "Se cerro el archivo correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "No hay un archivo abierto actualmente para cerrarlo");
        }

    }//GEN-LAST:event_jb_cerrarArchivoActionPerformed

    private void jb_EliminarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_EliminarCamposActionPerformed
        if (c.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay campos");
        } else {
            DefaultListModel lm = new DefaultListModel();
            lm.addAll(c);
            jl_eliminarCampo.setModel(lm);
            jtb_Campos.setSelectedIndex(3);
        }
    }//GEN-LAST:event_jb_EliminarCamposActionPerformed

    private void jb_archivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_archivosActionPerformed
        Menu.setSelectedIndex(0);
        MenuMenus.setSelectedIndex(0);
    }//GEN-LAST:event_jb_archivosActionPerformed

    private void jb_registrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registrosActionPerformed
        if (m.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe tener Campos Salvados");
        } else {
            DefaultTableModel mr = new DefaultTableModel();
            Object[] tempi = new Object[m.getLista().size()];
            mr.addRow(tempi);
            for (int i = 0; i < m.getLista().size(); i++) {
                mr.addColumn(m.getLista().get(i).getNombre());
            }

            jt_introR.setModel(mr);

            Menu.setSelectedIndex(2);
            MenuMenus.setSelectedIndex(2);
            jtp_registros.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jb_registrosActionPerformed

    private void jb_estandarizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_estandarizacionActionPerformed
        Menu.setSelectedIndex(4);
        MenuMenus.setSelectedIndex(4);
    }//GEN-LAST:event_jb_estandarizacionActionPerformed

    private void jb_crearCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearCamposActionPerformed
        jtb_Campos.setSelectedIndex(0);
    }//GEN-LAST:event_jb_crearCamposActionPerformed

    private void jcb_tipoDeDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_tipoDeDatoActionPerformed
        if (jcb_tipoDeDato.getSelectedItem().equals("Boolean") || jcb_tipoDeDato.getSelectedItem().equals("Char ")) {
            jl_llavePrimaria.setForeground(Color.gray);
            jl_longitud.setForeground(Color.gray);
            jcb_llavePrimaria.setEnabled(false);
            js_longitud.setEnabled(false);
            js_longitud.setValue(1);
            jcb_llavePrimaria.setSelected(false);
        } else {
            jl_llavePrimaria.setForeground(Color.white);
            jl_longitud.setForeground(Color.white);
            jcb_llavePrimaria.setEnabled(true);
            js_longitud.setEnabled(true);
        }


    }//GEN-LAST:event_jcb_tipoDeDatoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean check = true;
        for (int i = 0; i < c.size(); i++) {
            if (jtf_nombreCampo.getText().equals(c.get(i).getNombre())) {
                JOptionPane.showMessageDialog(this, "El nombre ya esta usado");
                check = false;
            }
        }
        if (jtf_nombreCampo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El campo debe tener un nombre");
            check = false;
        }

        if (check) {
            if (jcb_tipoDeDato.getSelectedItem().equals("Boolean")) {
                c.add(new Campos(jtf_nombreCampo.getText(), (String) jcb_tipoDeDato.getSelectedItem(), -1, false));
            } else {
                if (jcb_llavePrimaria.isSelected()) {
                    for (int i = 0; i < c.size(); i++) {
                        if (c.get(i).isLlaveP()) {
                            c.get(i).setLlaveP(false);
                        }
                    }
                }
                c.add(new Campos(jtf_nombreCampo.getText(), (String) jcb_tipoDeDato.getSelectedItem(), (int) js_longitud.getValue(), jcb_llavePrimaria.isSelected()));
            }
            jtf_nombreCampo.setText("");
            jcb_tipoDeDato.setSelectedIndex(0);
            js_longitud.setValue(1);
            jcb_llavePrimaria.setSelected(false);

            if (c.size() > 10) {
                JOptionPane.showMessageDialog(rootPane, "Hay un maximo de 10 Campos");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb_ListarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ListarCamposActionPerformed
        if (c.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay campos");
        } else {
            DefaultTableModel tm = (DefaultTableModel) jt_listarCampos.getModel();
            tm.setRowCount(0);
            for (int i = 0; i < c.size(); i++) {
                Object[] temp = new Object[4];
                temp[0] = c.get(i).getNombre();
                temp[1] = c.get(i).getTipo();
                temp[2] = c.get(i).getLongitud();
                temp[3] = c.get(i).isLlaveP();
                tm.addRow(temp);
                //hola :3
            }
            jtb_Campos.setSelectedIndex(1);
        }
    }//GEN-LAST:event_jb_ListarCamposActionPerformed

    private void jb_modificarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarCamposActionPerformed
        if (c.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay campos");
        } else {
            DefaultTableModel tm = (DefaultTableModel) jt_modificarCampos.getModel();
            tm.setRowCount(0);
            for (int i = 0; i < c.size(); i++) {
                Object[] temp = new Object[4];
                temp[0] = c.get(i).getNombre();
                temp[1] = c.get(i).getTipo();
                temp[2] = c.get(i).getLongitud();
                temp[3] = c.get(i).isLlaveP();
                tm.addRow(temp);
            }
            jtb_Campos.setSelectedIndex(2);
        }
    }//GEN-LAST:event_jb_modificarCamposActionPerformed

    private void jb_modificarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarCampoActionPerformed
        boolean check = true;
        int contLP = 0;
        DefaultTableModel tm = (DefaultTableModel) jt_modificarCampos.getModel();
        for (int i = 0; i < c.size(); i++) {
            if (tm.getValueAt(i, 1).equals("Boolean")) {
                if ((int) tm.getValueAt(i, 2) != -1 || tm.getValueAt(i, 3).equals(true)) {
                    tm.setValueAt(-1, i, 2);
                    tm.setValueAt(false, i, 3);
                }
            } else {
                if (tm.getValueAt(i, 3).equals(true)) {
                    contLP++;
                }
                if (tm.getValueAt(i, 1).equals("String") || tm.getValueAt(i, 1).equals("Integer") || tm.getValueAt(i, 1).equals("Double")
                        || tm.getValueAt(i, 1).equals("Float") || tm.getValueAt(i, 1).equals("Byte") || tm.getValueAt(i, 1).equals("Char")
                        || tm.getValueAt(i, 1).equals("Byte") || tm.getValueAt(i, 1).equals("Short")) {
                } else {
                    JOptionPane.showMessageDialog(this, "El tipo de dato ingresado no es valido");
                    check = false;
                }
                if ((int) tm.getValueAt(i, 2) < 1) {
                    JOptionPane.showMessageDialog(this, "Campos deben tener minimo 1 de longitud (excepto boolean)");
                    check = false;
                }
            }
        }
        if (contLP != 1) {
            JOptionPane.showMessageDialog(this, "Solo puede tener una llave primaria");
            check = false;
        }

        if (!check) {
            JOptionPane.showMessageDialog(this, "Las modificaciones que hizo no son validas");
        } else {
            for (int i = 0; i < c.size(); i++) {
                c.get(i).setNombre((String) tm.getValueAt(i, 0));
                c.get(i).setTipo((String) tm.getValueAt(i, 1));
                c.get(i).setLongitud((int) tm.getValueAt(i, 2));
                c.get(i).setLlaveP((boolean) tm.getValueAt(i, 3));
            }
            JOptionPane.showMessageDialog(this, "Modificado correctamente");
        }
    }//GEN-LAST:event_jb_modificarCampoActionPerformed

    private void jb_eliminarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarCampoActionPerformed
        if (jl_eliminarCampo.getSelectedIndex() != -1) {
            c.remove(jl_eliminarCampo.getSelectedIndex());
            DefaultListModel lm = new DefaultListModel();
            lm.addAll(c);
            jl_eliminarCampo.setModel(lm);
        }
    }//GEN-LAST:event_jb_eliminarCampoActionPerformed

    private void jb_nuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_nuevoArchivoActionPerformed
        String nombre = JOptionPane.showInputDialog(null, "Ingrese el nombre del archivo");
        nomi = nombre;
        try {
            archivo = new RandomAccessFile("./" + nombre + ".txt", "rws");
            btreeFile = new File("./" + nombre + "BT.txt");
            btreeFile.createNewFile();
            bta = new BTreeAdmin(btreeFile);
            arbol = new BTree(2);

            bta.setTree(arbol);
            bta.escribirArbol();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
        }
        File prueba = new File("./" + nombre + ".txt");
        System.out.println(nombre);
        try {
            if (prueba.createNewFile()) {
                JOptionPane.showMessageDialog(null, "Se ha creado el archivo correctamente");
                holder = prueba;
            }
        } catch (IOException ex) {
            Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_nuevoArchivoActionPerformed

    private void jb_abrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_abrirArchivoActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text Files", "txt");
        fc.setFileFilter(filter);
        fc.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int returnValue = fc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(null, "Se ha abierto el archivo correctamente");

            try {
                archivo = new RandomAccessFile(fc.getSelectedFile(), "rws");
                holder = fc.getSelectedFile();

                nomi = fc.getSelectedFile().getName().substring(0, fc.getSelectedFile().getName().length() - 4);
                System.out.println(nomi);
                btreeFile = new File("./" + nomi + "BT.txt");
                bta = new BTreeAdmin(btreeFile);
                bta.cargarArbol();
                arbol = bta.getTree();
                if (arbol == null) {
                    arbol = new BTree(6);
                }
                arbol.printTree();

                //Cargar metadata
                //Carga los campos
                m = new MetaData();
                String campos = archivo.readLine();
                if (campos == null) {
                    JOptionPane.showMessageDialog(this, "El archivo esta vacio");
                } else {
                    String Camp = "";
                    ArrayList atris = new ArrayList();
                    for (int i = 0; i < campos.length(); i++) {
                        if (campos.charAt(i) == '|') {
                            atris.add(Camp);
                            Camp = "";
                        } else if (campos.charAt(i) == ',' || i == campos.length() - 1) {
                            m.getLista().add(new Campos((String) atris.get(0), (String) atris.get(1), Integer.parseInt((String) atris.get(2)), Boolean.parseBoolean(Camp)));
                            c.add(new Campos((String) atris.get(0), (String) atris.get(1), Integer.parseInt((String) atris.get(2)), Boolean.parseBoolean(Camp)));
                            Camp = "";
                            atris = new ArrayList();
                        } else {
                            Camp += campos.charAt(i);
                        }
                    }
                    //Carga el resto de los atributos
                    m.setLongitud(Integer.parseInt(archivo.readLine().replaceAll("[^0-9]", "")));
                    m.setCantidad(Integer.parseInt(archivo.readLine().replaceAll("[^0-9]", "")));
                    m.setCabezaA(Integer.parseInt(archivo.readLine().replaceAll("[^0-9]", "")));
                    System.out.println(m.toString2());
                }

            } catch (FileNotFoundException ex) {
                Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Occurio un error al tratar de abrir el archivo");
        }


    }//GEN-LAST:event_jb_abrirArchivoActionPerformed

    private void jb_salvarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarArchivoActionPerformed
        if (archivo == null) {
            JOptionPane.showMessageDialog(this, "No tiene un archivo abierto");
        } else if (c.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay campos");
        } else if (!arbol.getRoot().keys.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No puede salvar el archivo porque ya tiene registros");
        } else if (!m.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ya tiene Campos salvados");
        } else {
            try {
                archivo.setLength(0);
                archivo.seek(0);
                if (!c.isEmpty()) {
                    m.setLista(c);
                }
                archivo.writeBytes(m.toString());
                JOptionPane.showMessageDialog(this, "Los campos fueron salvados");
            } catch (IOException ex) {
                Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

//        String escribir = "";
//        boolean check = false;
//        for (int i = 0; i < c.size(); i++) {
//            if (c.get(i).isLlaveP()) {
//                check = true;
//            }
//        }
//        if (archivo == null) {
//            JOptionPane.showMessageDialog(null, "Debe crear o abrir un archivo");
//
//        } else {
//            if (!c.isEmpty()) {
//                if (check) {
//                    for (int i = 0; i < c.size(); i++) {
//                        escribir += c.get(i).getNombre() + "|" + c.get(i).getTipo() + "|" + c.get(i).getLongitud() + delim + c.get(i).isLlaveP();
//                        if (!(i == c.size() - 1)) {
//                            escribir += ";";
//                        }
//                    }
//                    try (BufferedWriter bw = new BufferedWriter(new FileWriter(archivo))) {
//                        bw.write(escribir);
//                        System.out.println("File written successfully.");
//                    } catch (IOException e) {
//                        e.printStackTrace();
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(this, "Debe haber una llave primaria");
//                }
//            
//            
//            } else {
//                JOptionPane.showMessageDialog(null, "Debe crear Campos");
//            }
//
//        }
    }//GEN-LAST:event_jb_salvarArchivoActionPerformed

    private void jtf_nombreCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombreCampoActionPerformed
        // js_longitud.setValue(((String)jtf_nombreCampo.getText()).length());
    }//GEN-LAST:event_jtf_nombreCampoActionPerformed

    private void jtf_nombreCampoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombreCampoKeyTyped
        //js_longitud.setValue(((String)jtf_nombreCampo.getText()).length());
    }//GEN-LAST:event_jtf_nombreCampoKeyTyped

    private void jtf_nombreCampoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombreCampoKeyPressed
        // js_longitud.setValue(((String)jtf_nombreCampo.getText()).length());
    }//GEN-LAST:event_jtf_nombreCampoKeyPressed

    private void jtf_nombreCampoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombreCampoKeyReleased
        //js_longitud.setValue(((String)jtf_nombreCampo.getText()).length());
    }//GEN-LAST:event_jtf_nombreCampoKeyReleased

    private void jb_nuevoArchivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_nuevoArchivo1ActionPerformed
        jtp_registros.setSelectedIndex(0);
    }//GEN-LAST:event_jb_nuevoArchivo1ActionPerformed

    private void jb_abrirArchivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_abrirArchivo1ActionPerformed
        jtp_registros.setSelectedIndex(1);
    }//GEN-LAST:event_jb_abrirArchivo1ActionPerformed

    private void jb_salvarArchivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarArchivo1ActionPerformed

        DefaultTableModel mr = new DefaultTableModel();
        for (int i = 0; i < m.getLista().size(); i++) {
            mr.addColumn(m.getLista().get(i).getNombre());
        }
        jt_buscarR.setModel(mr);
        int key = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el registro que desea buscar"));
        if (arbol.search(key) == null) {
            JOptionPane.showMessageDialog(this, "No fue encontrado");
        } else {

        }
        jtp_registros.setSelectedIndex(2);
    }//GEN-LAST:event_jb_salvarArchivo1ActionPerformed

    private void jb_cerrarArchivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cerrarArchivo1ActionPerformed
        jtp_registros.setSelectedIndex(3);
    }//GEN-LAST:event_jb_cerrarArchivo1ActionPerformed

    private void jb_cerrarArchivo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cerrarArchivo2ActionPerformed

        DefaultTableModel mr = new DefaultTableModel();
        for (int i = 0; i < m.getLista().size(); i++) {
            mr.addColumn(m.getLista().get(i).getNombre());
        }

        try {
            archivo.seek(m.toString().length());
            String reg = "";
            for (int i = 0; i < 10; i++) {
                reg = archivo.readLine();
                System.out.println(reg);
                if (reg == null) {
                    break;
                }
                String reg1 = "";
                ArrayList datosl = new ArrayList();
                for (int j = 0; j < reg.length(); j++) {
                    switch (reg.charAt(j)) {
                        case '|' -> {
                            datosl.add(reg1);
                            reg1 = "";
                        }
                        case '$' -> {
                            datosl.add(reg1);
                            reg1 = "";
                        }
                        default ->
                            reg1 += reg.charAt(j);
                    }
                }
                Object[] row = datosl.toArray();
                mr.addRow(row);
                reg = "";
                //archivo.skipBytes((m.getLongitud())+ 1);
                //archivo.seek(m.toString().length() + ((i+1) * m.getLongitud()));
            }

        } catch (IOException ex) {
            Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
        }
        jt_listarRegistro.setModel(mr);

        jtp_registros.setSelectedIndex(4);
    }//GEN-LAST:event_jb_cerrarArchivo2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean check = true;
        DefaultTableModel mr = (DefaultTableModel) jt_introR.getModel();
        String regi = "";

        for (int i = 0; i < m.getLista().size(); i++) {
            if (i == m.getLista().size() - 1) {
                if (mr.getValueAt(0, i) == null || mr.getValueAt(0, i).equals("")) {
                    JOptionPane.showMessageDialog(this, "El campo de " + m.getLista().get(i).getNombre() + "esta vacio");
                    check = false;

                } else if (m.getLista().get(i).getLongitud() < ((String) mr.getValueAt(0, i)).length() || mr.getValueAt(0, i) == null) {
                    JOptionPane.showMessageDialog(this, "La longitud de " + m.getLista().get(i).getNombre() + " excede");
                    check = false;
                } else {
                    regi += mr.getValueAt(0, i) + "\n";
                }
            } else {
                if (mr.getValueAt(0, i) == null || mr.getValueAt(0, i).equals("")) {
                    JOptionPane.showMessageDialog(this, "El campo de " + m.getLista().get(i).getNombre() + "esta vacio");
                    check = false;

                } else if (m.getLista().get(i).getLongitud() < ((String) mr.getValueAt(0, i)).length() || mr.getValueAt(0, i) == null) {
                    JOptionPane.showMessageDialog(this, "La longitud de " + m.getLista().get(i).getNombre() + " excede");
                    check = false;
                } else {
                    regi += mr.getValueAt(0, i) + "|";
                }

            }
        }
        //insertar al arbol

        if (arbol.getRoot() == null) {
            BTreeNode nuevo = new BTreeNode(arbol.getT(), check);
            arbol.getRoot().children.add(nuevo);
        }
        for (int i = 0; i < m.getLista().size(); i++) {
            if (m.getLista().get(i).isLlaveP()) {
                if ((arbol.search(Integer.parseInt((String) mr.getValueAt(0, i))) == null)) {
                    arbol.insert(Integer.parseInt((String) mr.getValueAt(0, i)));
                    arbol.printTree();
                } else {
                    JOptionPane.showMessageDialog(this, "Ya existe esta llave");
                }

            }
        }
        bta.setTree(arbol);
        bta.escribirArbol();

        mr.removeRow(0);
        Object[] tempi = new Object[m.getLista().size()];
        mr.addRow(tempi);
        jt_introR.setModel(mr);
        //insertar registro al archivo
        try {
            if (check) {
                if (regi.length() <= m.getLongitud()) {
                    regi = regi.substring(0, regi.length() - 1);
                    for (int i = regi.length(); i < m.getLongitud(); i++) {
                        regi += "$";
                    }
                    if (regi.length() == m.getLongitud() - 1) {
                        regi += "$";
                    }
                }
                int cont;
                if (m.getCantidad() == 0) {
                    cont = m.toString().length() + (m.getCantidad() * m.getLongitud());
                } else {
                    cont = m.toString().length() + (m.getCantidad() * m.getLongitud());
                }
                m.setCantidad(m.getCantidad() + 1); //actualizar cantidad

                archivo.seek(cont);
                archivo.readLine();
                archivo.writeBytes(regi + "\r\n");
            }
        } catch (IOException ex) {
            Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
        }

        //actualizar metadata
        try {
//          archivo.setLength(0);
            archivo.seek(0);
            if (!c.isEmpty()) {
                m.setLista(c);
            }
            archivo.writeBytes(m.toString());

        } catch (IOException ex) {
            Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jb_nuevoArchivo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_nuevoArchivo2ActionPerformed
        File excel = new File("./" + nomi + "E.csv");
        try {
            excel.createNewFile();

            archivo.seek(m.toString().length());
            String reg = "";
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(excel))) {
                String cam = "";
                for (int i = 0; i < m.getLista().size(); i++) {
                    if (i == m.getLista().size() - 1) {
                        cam += m.getLista().get(i).getNombre() + "\n";
                    } else {
                        cam += m.getLista().get(i).getNombre() + ",";
                    }

                }
                writer.write(cam);
                for (int i = 0; i < m.getCantidad(); i++) {
                    reg = archivo.readLine();
                    String regi = "";
                    for (int j = 0; j < reg.length(); j++) {
                        if (reg.charAt(j) == '$' || reg.charAt(j) == reg.length() - 1) {
                            regi += "\n";
                            break;
                        } else if (reg.charAt(j) == '|') {
                            regi += ",";
                        } else {
                            regi += reg.charAt(j);
                        }
                    }
                    System.out.println(regi);
                    writer.write(regi);
                }
            } catch (IOException e) {
            }

        } catch (IOException ex) {
            Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_nuevoArchivo2ActionPerformed

    private void jb_abrirArchivo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_abrirArchivo2ActionPerformed
        if(archivo== null){
            JOptionPane.showMessageDialog(null, "No hay un archivo abierto para poder hacerlo XML");
        }else{
           // JAXBContext content = JAXBContext.newInstance(classesToBeBound);
        }
    }//GEN-LAST:event_jb_abrirArchivo2ActionPerformed

    
    private void jb_salvarArchivo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarArchivo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarArchivo2ActionPerformed

    private void jb_cerrarArchivo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cerrarArchivo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_cerrarArchivo3ActionPerformed

    private void jb_nuevoArchivo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_nuevoArchivo3ActionPerformed

    }//GEN-LAST:event_jb_nuevoArchivo3ActionPerformed

    private void jb_abrirArchivo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_abrirArchivo3ActionPerformed
        Campos cc = jl_crearIndice.getSelectedValue();
        int cont = m.getLista().indexOf(cc), k = 0;
        try {
            archivo.seek(m.getLongitud());
            String reg = "";
            for (int i = 0; i < m.getCantidad(); i++) {
                reg = archivo.readLine();
                int conti = 1;
                String regi = ""; //string que se va a usar para agarrar la llave
                for (int j = 0; j < reg.length(); j++) {
                    if (conti == cont) {
                        if (reg.charAt(j) == '|') {
                            break;
                        }
                        regi += reg.charAt(j);
                    } else if (reg.charAt(j) == '|') {
                        cont++;
                    }
                }
                //AQUI SE TIENE QUE CONVERTIR LA LLAVE (regi) a llave k con hash
                arbolito.insert(k);
                bta2.setTree(arbolito);
                bta2.escribirArbol();
            }
        } catch (IOException ex) {
            Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_abrirArchivo3ActionPerformed

    private void jb_salvarArchivo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarArchivo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarArchivo3ActionPerformed

    private void jb_cerrarArchivo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cerrarArchivo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_cerrarArchivo4ActionPerformed

    private void jb_nuevoArchivo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_nuevoArchivo4ActionPerformed
        if (jl_crearIndice.getSelectedIndex() != -1) {
            File arbol2 = new File("./" + nomi + "BT2.txt");
            try {
                arbol2.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
            }
            bta2.setArchivo(arbol2);
            bta2.setTree(arbolito);

            cc = jl_crearIndice.getSelectedValue();
            int cont = m.getLista().indexOf(cc), k = 0;
            try {
                archivo.seek(m.getLongitud());
                String reg = "";
                for (int i = 0; i < m.getCantidad(); i++) {
                    reg = archivo.readLine();
                    int conti = 1;
                    String regi = ""; //string que se va a usar para agarrar la llave
                    for (int j = 0; j < reg.length(); j++) {
                        if (conti == cont) {
                            if (reg.charAt(j) == '|') {
                                break;
                            }
                            regi += reg.charAt(j);
                        } else if (reg.charAt(j) == '|') {
                            cont++;
                        }
                    }
                    //AQUI SE TIENE QUE CONVERTIR LA LLAVE (regi) a llave k con hash
                    arbolito.insert(k);
                    bta2.setTree(arbolito);
                    bta2.escribirArbol();
                }
            } catch (IOException ex) {
                Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jb_nuevoArchivo4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JTabbedPane MenuMenus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton jb_EliminarCampos;
    private javax.swing.JButton jb_ListarCampos;
    private javax.swing.JButton jb_abrirArchivo;
    private javax.swing.JButton jb_abrirArchivo1;
    private javax.swing.JButton jb_abrirArchivo2;
    private javax.swing.JButton jb_abrirArchivo3;
    private javax.swing.JButton jb_archivos;
    private javax.swing.JButton jb_campos;
    private javax.swing.JButton jb_cerrar;
    private javax.swing.JButton jb_cerrarArchivo;
    private javax.swing.JButton jb_cerrarArchivo1;
    private javax.swing.JButton jb_cerrarArchivo2;
    private javax.swing.JButton jb_cerrarArchivo3;
    private javax.swing.JButton jb_cerrarArchivo4;
    private javax.swing.JButton jb_crearCampos;
    private javax.swing.JButton jb_eliminarCampo;
    private javax.swing.JButton jb_estandarizacion;
    private javax.swing.JButton jb_indices;
    private javax.swing.JButton jb_modificarCampo;
    private javax.swing.JButton jb_modificarCampos;
    private javax.swing.JButton jb_nuevoArchivo;
    private javax.swing.JButton jb_nuevoArchivo1;
    private javax.swing.JButton jb_nuevoArchivo2;
    private javax.swing.JButton jb_nuevoArchivo3;
    private javax.swing.JButton jb_nuevoArchivo4;
    private javax.swing.JButton jb_registros;
    private javax.swing.JButton jb_salvarArchivo;
    private javax.swing.JButton jb_salvarArchivo1;
    private javax.swing.JButton jb_salvarArchivo2;
    private javax.swing.JButton jb_salvarArchivo3;
    private javax.swing.JCheckBox jcb_llavePrimaria;
    private javax.swing.JComboBox<String> jcb_tipoDeDato;
    private javax.swing.JList<Campos> jl_crearIndice;
    private javax.swing.JList<Campos> jl_eliminarCampo;
    private javax.swing.JLabel jl_llavePrimaria;
    private javax.swing.JLabel jl_longitud;
    private javax.swing.JPanel jp_archivos;
    private javax.swing.JPanel jp_campos;
    private javax.swing.JPanel jp_crearCampos;
    private javax.swing.JPanel jp_eliminarCampos;
    private javax.swing.JPanel jp_introducirregistros;
    private javax.swing.JPanel jp_listarCampos;
    private javax.swing.JPanel jp_modificarCampos;
    private javax.swing.JPanel jp_registros;
    private javax.swing.JPanel jp_seleccion;
    private javax.swing.JSpinner js_longitud;
    private javax.swing.JTable jt_buscarR;
    private javax.swing.JTable jt_introR;
    private javax.swing.JTable jt_listarCampos;
    private javax.swing.JTable jt_listarRegistro;
    private javax.swing.JTable jt_modificarCampos;
    private javax.swing.JTabbedPane jtb_Campos;
    private javax.swing.JTextField jtf_nombreCampo;
    private javax.swing.JTabbedPane jtp_registros;
    // End of variables declaration//GEN-END:variables
    ArrayList<Campos> c = new ArrayList();
    Campos cc;
    RandomAccessFile archivo;
    BufferedWriter bw;
    String delim;
    MetaData m = new MetaData();
    BTree arbol = new BTree(2), arbolito = new BTree(3);
    File btreeFile, holder;
    BTreeAdmin bta, bta2;
    String nomi;
}
