/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoestru2;

import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samue
 */
public class Proy extends javax.swing.JFrame {

    /**
     * Creates new form Proy
     */
    public Proy() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        Menu.setLayout(new CardLayout());
        MenuMenus.setLayout(new CardLayout());
        jtb_Campos.setLayout(new CardLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_seleccion = new javax.swing.JPanel();
        jb_archivos = new javax.swing.JButton();
        jb_campos = new javax.swing.JButton();
        jb_registros = new javax.swing.JButton();
        jb_indices = new javax.swing.JButton();
        jb_estandarizacion = new javax.swing.JButton();
        jb_cerrar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Menu = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jb_nuevoArchivo = new javax.swing.JButton();
        jb_abrirArchivo = new javax.swing.JButton();
        jb_salvarArchivo = new javax.swing.JButton();
        jb_cerrarArchivo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jb_crearCampos = new javax.swing.JButton();
        jb_ListarCampos = new javax.swing.JButton();
        jb_modificarCampos = new javax.swing.JButton();
        jb_EliminarCampos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        MenuMenus = new javax.swing.JTabbedPane();
        jp_archivos = new javax.swing.JPanel();
        jp_campos = new javax.swing.JPanel();
        jtb_Campos = new javax.swing.JTabbedPane();
        jp_crearCampos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_nombreCampo = new javax.swing.JTextField();
        jl_longitud = new javax.swing.JLabel();
        js_longitud = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jcb_tipoDeDato = new javax.swing.JComboBox<>();
        jl_llavePrimaria = new javax.swing.JLabel();
        jcb_llavePrimaria = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jp_listarCampos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_listarCampos = new javax.swing.JTable();
        jp_modificarCampos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_modificarCampos = new javax.swing.JTable();
        jb_modificarCampo = new javax.swing.JButton();
        jp_eliminarCampos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_eliminarCampo = new javax.swing.JList<>();
        jb_eliminarCampo = new javax.swing.JButton();
        jp_registros = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jp_seleccion.setBackground(new java.awt.Color(102, 102, 102));

        jb_archivos.setBackground(new java.awt.Color(204, 255, 255));
        jb_archivos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_archivos.setText("Archivos");
        jb_archivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_archivosActionPerformed(evt);
            }
        });

        jb_campos.setBackground(new java.awt.Color(204, 204, 255));
        jb_campos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_campos.setText("Campos");
        jb_campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_camposActionPerformed(evt);
            }
        });

        jb_registros.setBackground(new java.awt.Color(255, 204, 204));
        jb_registros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_registros.setText("Registros");
        jb_registros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registrosActionPerformed(evt);
            }
        });

        jb_indices.setBackground(new java.awt.Color(255, 255, 204));
        jb_indices.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_indices.setText("Indices");
        jb_indices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_indicesActionPerformed(evt);
            }
        });

        jb_estandarizacion.setBackground(new java.awt.Color(204, 255, 204));
        jb_estandarizacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_estandarizacion.setText("Estand.");
        jb_estandarizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_estandarizacionActionPerformed(evt);
            }
        });

        jb_cerrar.setBackground(new java.awt.Color(255, 102, 102));
        jb_cerrar.setText("Cerrar");
        jb_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cerrarActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(153, 204, 255));
        jButton7.setText("Regresar");

        javax.swing.GroupLayout jp_seleccionLayout = new javax.swing.GroupLayout(jp_seleccion);
        jp_seleccion.setLayout(jp_seleccionLayout);
        jp_seleccionLayout.setHorizontalGroup(
            jp_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_seleccionLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jb_archivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jb_campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jb_registros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jb_indices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jb_estandarizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addGroup(jp_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_seleccionLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jb_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jp_seleccionLayout.setVerticalGroup(
            jp_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_seleccionLayout.createSequentialGroup()
                .addGroup(jp_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_seleccionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jb_cerrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7))
                    .addGroup(jp_seleccionLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jp_seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_archivos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_campos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_indices, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_estandarizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Menu.setBackground(new java.awt.Color(102, 102, 102));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jb_nuevoArchivo.setText("Crear Archivo");
        jb_nuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_nuevoArchivoActionPerformed(evt);
            }
        });

        jb_abrirArchivo.setText("Abrir Archivo");
        jb_abrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_abrirArchivoActionPerformed(evt);
            }
        });

        jb_salvarArchivo.setText("Salvar Archivo");
        jb_salvarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarArchivoActionPerformed(evt);
            }
        });

        jb_cerrarArchivo.setText("Cerrar Archivo");
        jb_cerrarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cerrarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_cerrarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_salvarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_abrirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_nuevoArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jb_nuevoArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_abrirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_salvarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_cerrarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        Menu.addTab("tab1", jPanel4);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jb_crearCampos.setText("Crear");
        jb_crearCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearCamposActionPerformed(evt);
            }
        });

        jb_ListarCampos.setText("Listar");
        jb_ListarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ListarCamposActionPerformed(evt);
            }
        });

        jb_modificarCampos.setText("Modificar");
        jb_modificarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarCamposActionPerformed(evt);
            }
        });

        jb_EliminarCampos.setText("Eliminar");
        jb_EliminarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_EliminarCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_EliminarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_modificarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_ListarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_crearCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jb_crearCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_ListarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_modificarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_EliminarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        Menu.addTab("tab2", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        Menu.addTab("tab3", jPanel3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        Menu.addTab("tab4", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        Menu.addTab("tab5", jPanel6);

        javax.swing.GroupLayout jp_archivosLayout = new javax.swing.GroupLayout(jp_archivos);
        jp_archivos.setLayout(jp_archivosLayout);
        jp_archivosLayout.setHorizontalGroup(
            jp_archivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jp_archivosLayout.setVerticalGroup(
            jp_archivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        MenuMenus.addTab("archivo", jp_archivos);

        jtb_Campos.setBackground(new java.awt.Color(51, 51, 51));

        jp_crearCampos.setBackground(new java.awt.Color(51, 51, 51));
        jp_crearCampos.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de Campo");

        jtf_nombreCampo.setBackground(new java.awt.Color(51, 51, 51));
        jtf_nombreCampo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtf_nombreCampo.setForeground(new java.awt.Color(204, 204, 204));
        jtf_nombreCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombreCampoActionPerformed(evt);
            }
        });
        jtf_nombreCampo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_nombreCampoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_nombreCampoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_nombreCampoKeyTyped(evt);
            }
        });

        jl_longitud.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jl_longitud.setForeground(new java.awt.Color(255, 255, 255));
        jl_longitud.setText("Longitud");

        js_longitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        js_longitud.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de Dato");

        jcb_tipoDeDato.setBackground(new java.awt.Color(51, 51, 51));
        jcb_tipoDeDato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcb_tipoDeDato.setForeground(new java.awt.Color(255, 255, 255));
        jcb_tipoDeDato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "String", "Boolean", "Integer", "Char ", "Double", "Float", "Short", "Byte" }));
        jcb_tipoDeDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_tipoDeDatoActionPerformed(evt);
            }
        });

        jl_llavePrimaria.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jl_llavePrimaria.setForeground(new java.awt.Color(255, 255, 255));
        jl_llavePrimaria.setText("Llave Primaria");

        jcb_llavePrimaria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_crearCamposLayout = new javax.swing.GroupLayout(jp_crearCampos);
        jp_crearCampos.setLayout(jp_crearCamposLayout);
        jp_crearCamposLayout.setHorizontalGroup(
            jp_crearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_crearCamposLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jp_crearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_llavePrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_llavePrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_nombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_tipoDeDato, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_crearCamposLayout.setVerticalGroup(
            jp_crearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_crearCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_nombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jl_longitud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_tipoDeDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jl_llavePrimaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_llavePrimaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtb_Campos.addTab("crear", jp_crearCampos);

        jp_listarCampos.setBackground(new java.awt.Color(51, 51, 51));

        jt_listarCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo de Dato", "Longitud", "Llave Primaria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_listarCampos);

        javax.swing.GroupLayout jp_listarCamposLayout = new javax.swing.GroupLayout(jp_listarCampos);
        jp_listarCampos.setLayout(jp_listarCamposLayout);
        jp_listarCamposLayout.setHorizontalGroup(
            jp_listarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_listarCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp_listarCamposLayout.setVerticalGroup(
            jp_listarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_listarCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtb_Campos.addTab("listar", jp_listarCampos);

        jt_modificarCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo de Dato", "Longitud", "Llave Primaria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_modificarCampos);

        jb_modificarCampo.setText("Modificar");
        jb_modificarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarCampoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_modificarCamposLayout = new javax.swing.GroupLayout(jp_modificarCampos);
        jp_modificarCampos.setLayout(jp_modificarCamposLayout);
        jp_modificarCamposLayout.setHorizontalGroup(
            jp_modificarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificarCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_modificarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                    .addGroup(jp_modificarCamposLayout.createSequentialGroup()
                        .addComponent(jb_modificarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jp_modificarCamposLayout.setVerticalGroup(
            jp_modificarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificarCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jb_modificarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jtb_Campos.addTab("modificar", jp_modificarCampos);

        jScrollPane3.setViewportView(jl_eliminarCampo);

        jb_eliminarCampo.setText("Eliminar");
        jb_eliminarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarCampoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_eliminarCamposLayout = new javax.swing.GroupLayout(jp_eliminarCampos);
        jp_eliminarCampos.setLayout(jp_eliminarCamposLayout);
        jp_eliminarCamposLayout.setHorizontalGroup(
            jp_eliminarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_eliminarCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jp_eliminarCamposLayout.createSequentialGroup()
                .addComponent(jb_eliminarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_eliminarCamposLayout.setVerticalGroup(
            jp_eliminarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_eliminarCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jb_eliminarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtb_Campos.addTab("eliminar", jp_eliminarCampos);

        javax.swing.GroupLayout jp_camposLayout = new javax.swing.GroupLayout(jp_campos);
        jp_campos.setLayout(jp_camposLayout);
        jp_camposLayout.setHorizontalGroup(
            jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtb_Campos)
        );
        jp_camposLayout.setVerticalGroup(
            jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtb_Campos)
        );

        MenuMenus.addTab("campo", jp_campos);

        javax.swing.GroupLayout jp_registrosLayout = new javax.swing.GroupLayout(jp_registros);
        jp_registros.setLayout(jp_registrosLayout);
        jp_registrosLayout.setHorizontalGroup(
            jp_registrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jp_registrosLayout.setVerticalGroup(
            jp_registrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        MenuMenus.addTab("registro", jp_registros);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        MenuMenus.addTab("indice", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_seleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuMenus)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu)
                    .addComponent(MenuMenus))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_camposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_camposActionPerformed
        Menu.setSelectedIndex(1);
        MenuMenus.setSelectedIndex(1);
    }//GEN-LAST:event_jb_camposActionPerformed

    private void jb_indicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_indicesActionPerformed
        Menu.setSelectedIndex(3);
        MenuMenus.setSelectedIndex(3);
    }//GEN-LAST:event_jb_indicesActionPerformed

    private void jb_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jb_cerrarActionPerformed

    private void jb_cerrarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cerrarArchivoActionPerformed
        if(archivo != null){
            archivo= null;
            JOptionPane.showMessageDialog(null, "Se cerro el archivo correctamente");
        }else{
            JOptionPane.showMessageDialog(null, "No hay un archivo abierto actualmente para cerrarlo");
        }
        
    }//GEN-LAST:event_jb_cerrarArchivoActionPerformed

    private void jb_EliminarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_EliminarCamposActionPerformed
        if (c.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay campos");
        } else {
            DefaultListModel lm = new DefaultListModel();
            lm.addAll(c);
            jl_eliminarCampo.setModel(lm);
            jtb_Campos.setSelectedIndex(3);
        }
    }//GEN-LAST:event_jb_EliminarCamposActionPerformed

    private void jb_archivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_archivosActionPerformed
        Menu.setSelectedIndex(0);
        MenuMenus.setSelectedIndex(0);
    }//GEN-LAST:event_jb_archivosActionPerformed

    private void jb_registrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registrosActionPerformed
        Menu.setSelectedIndex(2);
        MenuMenus.setSelectedIndex(2);
    }//GEN-LAST:event_jb_registrosActionPerformed

    private void jb_estandarizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_estandarizacionActionPerformed
        Menu.setSelectedIndex(4);
        MenuMenus.setSelectedIndex(4);
    }//GEN-LAST:event_jb_estandarizacionActionPerformed

    private void jb_crearCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearCamposActionPerformed
        jtb_Campos.setSelectedIndex(0);
    }//GEN-LAST:event_jb_crearCamposActionPerformed

    private void jcb_tipoDeDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_tipoDeDatoActionPerformed
        if (jcb_tipoDeDato.getSelectedItem().equals("Boolean")||jcb_tipoDeDato.getSelectedItem().equals("Char ")) {
            jl_llavePrimaria.setForeground(Color.gray);
            jl_longitud.setForeground(Color.gray);
            jcb_llavePrimaria.setEnabled(false);
            js_longitud.setEnabled(false);
            js_longitud.setValue(1);
            jcb_llavePrimaria.setSelected(false);
        } else {
            jl_llavePrimaria.setForeground(Color.white);
            jl_longitud.setForeground(Color.white);
            jcb_llavePrimaria.setEnabled(true);
            js_longitud.setEnabled(true);
        }
        if(jcb_tipoDeDato.getSelectedItem().equals("Integer")||jcb_tipoDeDato.getSelectedItem().equals("Double")||jcb_tipoDeDato.getSelectedItem().equals("Float")||jcb_tipoDeDato.getSelectedItem().equals("Short")||jcb_tipoDeDato.getSelectedItem().equals("Byte")){ //condicion para integer
            jl_llavePrimaria.setForeground(Color.gray);
            jl_longitud.setForeground(Color.gray);
            jcb_llavePrimaria.setEnabled(false);
            //js_longitud.setEnabled(true);
            js_longitud.setValue(1);
            jcb_llavePrimaria.setSelected(false);
        } //else {
//            jl_llavePrimaria.setForeground(Color.white);
//            jl_longitud.setForeground(Color.white);
//            jcb_llavePrimaria.setEnabled(true);
//            js_longitud.setEnabled(true);
//        }
        
    }//GEN-LAST:event_jcb_tipoDeDatoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean check = true;
        if (jtf_nombreCampo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El campo debe tener un nombre");
            check = false;
        }

        if (check) {
            if (jcb_tipoDeDato.getSelectedItem().equals("Boolean")) {
                c.add(new Campos(jtf_nombreCampo.getText(), (String) jcb_tipoDeDato.getSelectedItem(), -1, false));
            } else {
                if (jcb_llavePrimaria.isSelected()) {
                    for (int i = 0; i < c.size(); i++) {
                        if (c.get(i).isLlaveP()) {
                            c.get(i).setLlaveP(false);
                        }
                    }
                }
                c.add(new Campos(jtf_nombreCampo.getText(), (String) jcb_tipoDeDato.getSelectedItem(), (int) js_longitud.getValue(), jcb_llavePrimaria.isSelected()));
            }
            jtf_nombreCampo.setText("");
            jcb_tipoDeDato.setSelectedIndex(0);
            js_longitud.setValue(1);
            jcb_llavePrimaria.setSelected(false);

            if (c.size() > 10) {
                JOptionPane.showMessageDialog(rootPane, "Hay un maximo de 10 Campos");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb_ListarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ListarCamposActionPerformed
        if (c.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay campos");
        } else {
            DefaultTableModel tm = (DefaultTableModel) jt_listarCampos.getModel();
            tm.setRowCount(0);
            for (int i = 0; i < c.size(); i++) {
                Object[] temp = new Object[4];
                temp[0] = c.get(i).getNombre();
                temp[1] = c.get(i).getTipo();
                temp[2] = c.get(i).getLongitud();
                temp[3] = c.get(i).isLlaveP();
                tm.addRow(temp);
            }
            jtb_Campos.setSelectedIndex(1);
        }
    }//GEN-LAST:event_jb_ListarCamposActionPerformed

    private void jb_modificarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarCamposActionPerformed
        if (c.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay campos");
        } else {
            DefaultTableModel tm = (DefaultTableModel) jt_modificarCampos.getModel();
            tm.setRowCount(0);
            for (int i = 0; i < c.size(); i++) {
                Object[] temp = new Object[4];
                temp[0] = c.get(i).getNombre();
                temp[1] = c.get(i).getTipo();
                temp[2] = c.get(i).getLongitud();
                temp[3] = c.get(i).isLlaveP();
                tm.addRow(temp);
            }
            jtb_Campos.setSelectedIndex(2);
        }
    }//GEN-LAST:event_jb_modificarCamposActionPerformed

    private void jb_modificarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarCampoActionPerformed
        boolean check = true;
        int contLP = 0;
        DefaultTableModel tm = (DefaultTableModel) jt_modificarCampos.getModel();
        for (int i = 0; i < c.size(); i++) {
            if (tm.getValueAt(i, 1).equals("Boolean")) {
                if ((int) tm.getValueAt(i, 2) != -1 || tm.getValueAt(i, 3).equals(true)) {
                    check = false;
                }
            } else {
                if (tm.getValueAt(i, 3).equals(true)) {
                    contLP++;
                }
                if (tm.getValueAt(i, 1).equals("String") || tm.getValueAt(i, 1).equals("Integer") || tm.getValueAt(i, 1).equals("Double")
                        || tm.getValueAt(i, 1).equals("Float") || tm.getValueAt(i, 1).equals("Byte") || tm.getValueAt(i, 1).equals("Char")
                        || tm.getValueAt(i, 1).equals("float")) {
                } else {
                    check = false;
                }
                if ((int) tm.getValueAt(i, 2) < 1) {
                    check = false;
                }
            }
        }
        if (contLP > 1) {
            check = false;
        }

        if (!check) {
            JOptionPane.showMessageDialog(this, "Las modificaciones que hizo no son validas");
        } else {
            for (int i = 0; i < c.size(); i++) {
                c.get(i).setNombre((String) tm.getValueAt(i, 0));
                c.get(i).setTipo((String) tm.getValueAt(i, 1));
                c.get(i).setLongitud((int) tm.getValueAt(i, 2));
                c.get(i).setLlaveP((boolean) tm.getValueAt(i, 3));
            }
            JOptionPane.showMessageDialog(this, "Modificado correctamente");
        }
    }//GEN-LAST:event_jb_modificarCampoActionPerformed

    private void jb_eliminarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarCampoActionPerformed
        if (jl_eliminarCampo.getSelectedIndex() != -1) {
            c.remove(jl_eliminarCampo.getSelectedIndex());
            DefaultListModel lm = new DefaultListModel();
            lm.addAll(c);
            jl_eliminarCampo.setModel(lm);
        }
    }//GEN-LAST:event_jb_eliminarCampoActionPerformed

    private void jb_nuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_nuevoArchivoActionPerformed
        String nombre = JOptionPane.showInputDialog(null, "Ingrese el nombre del archivo");
        archivo = new File("./" + nombre + ".txt");
        System.out.println(nombre);
        try {
            if (archivo.createNewFile()) {
                JOptionPane.showMessageDialog(null, "Se ha creado el archivo correctamente");
            }
        } catch (IOException ex) {
            Logger.getLogger(Proy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_nuevoArchivoActionPerformed

    private void jb_abrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_abrirArchivoActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text Files", "txt");
        fc.setFileFilter(filter);
        fc.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int returnValue = fc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(null, "Se ha abierto el archivo correctamente");
            archivo = fc.getSelectedFile();
        }else{
            JOptionPane.showMessageDialog(null,"Occurio un error al tratar de abrir el archivo");
        }
    }//GEN-LAST:event_jb_abrirArchivoActionPerformed

    private void jb_salvarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarArchivoActionPerformed
        String escribir = "";
        if (archivo == null) {
            JOptionPane.showMessageDialog(null, "Debe crear o abrir un archivo");
        } else {
            if (!c.isEmpty()) {
                for (int i = 0; i < c.size(); i++) {
                    escribir += c.get(i).getNombre() + "|" + c.get(i).getTipo() + "|" + c.get(i).getLongitud() + "|" + c.get(i).isLlaveP();
                    if(!(i == c.size() - 1)){
                        escribir += ";";
                    }
                }
                try (BufferedWriter bw = new BufferedWriter(new FileWriter(archivo))) {
                    bw.write(escribir);
                    System.out.println("File written successfully.");
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Debe crear Campos");
            }

        }
    }//GEN-LAST:event_jb_salvarArchivoActionPerformed

    private void jtf_nombreCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombreCampoActionPerformed
      // js_longitud.setValue(((String)jtf_nombreCampo.getText()).length());
    }//GEN-LAST:event_jtf_nombreCampoActionPerformed

    private void jtf_nombreCampoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombreCampoKeyTyped
       //js_longitud.setValue(((String)jtf_nombreCampo.getText()).length());
    }//GEN-LAST:event_jtf_nombreCampoKeyTyped

    private void jtf_nombreCampoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombreCampoKeyPressed
      // js_longitud.setValue(((String)jtf_nombreCampo.getText()).length());
    }//GEN-LAST:event_jtf_nombreCampoKeyPressed

    private void jtf_nombreCampoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombreCampoKeyReleased
       //js_longitud.setValue(((String)jtf_nombreCampo.getText()).length());
    }//GEN-LAST:event_jtf_nombreCampoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JTabbedPane MenuMenus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_EliminarCampos;
    private javax.swing.JButton jb_ListarCampos;
    private javax.swing.JButton jb_abrirArchivo;
    private javax.swing.JButton jb_archivos;
    private javax.swing.JButton jb_campos;
    private javax.swing.JButton jb_cerrar;
    private javax.swing.JButton jb_cerrarArchivo;
    private javax.swing.JButton jb_crearCampos;
    private javax.swing.JButton jb_eliminarCampo;
    private javax.swing.JButton jb_estandarizacion;
    private javax.swing.JButton jb_indices;
    private javax.swing.JButton jb_modificarCampo;
    private javax.swing.JButton jb_modificarCampos;
    private javax.swing.JButton jb_nuevoArchivo;
    private javax.swing.JButton jb_registros;
    private javax.swing.JButton jb_salvarArchivo;
    private javax.swing.JCheckBox jcb_llavePrimaria;
    private javax.swing.JComboBox<String> jcb_tipoDeDato;
    private javax.swing.JList<Campos> jl_eliminarCampo;
    private javax.swing.JLabel jl_llavePrimaria;
    private javax.swing.JLabel jl_longitud;
    private javax.swing.JPanel jp_archivos;
    private javax.swing.JPanel jp_campos;
    private javax.swing.JPanel jp_crearCampos;
    private javax.swing.JPanel jp_eliminarCampos;
    private javax.swing.JPanel jp_listarCampos;
    private javax.swing.JPanel jp_modificarCampos;
    private javax.swing.JPanel jp_registros;
    private javax.swing.JPanel jp_seleccion;
    private javax.swing.JSpinner js_longitud;
    private javax.swing.JTable jt_listarCampos;
    private javax.swing.JTable jt_modificarCampos;
    private javax.swing.JTabbedPane jtb_Campos;
    private javax.swing.JTextField jtf_nombreCampo;
    // End of variables declaration//GEN-END:variables
    ArrayList<Campos> c = new ArrayList();
    File archivo;
    BufferedWriter bw;
}
